/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// Legacy defaults (fallbacks only). Prefer environment variables via Vite.
export const projectId = "cyqfwfkhbwthmfhhfpyz"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhnenlpZGxndmVubnJzem9sZXZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3MDM2OTIsImV4cCI6MjA2ODI3OTY5Mn0.cBXLvuTfGQbnQbfayyRzZ-W_azBc962Bpf8WH3DYoL4"

// Derived configuration – uses env when available
const envUrl = (typeof import.meta !== 'undefined' && (import.meta as any).env?.VITE_SUPABASE_URL)
  ? (import.meta as any).env.VITE_SUPABASE_URL as string
  : ''

export const baseUrl: string = envUrl || `https://${projectId}.supabase.co`
// Alias for clarity in other imports
export const projectUrl: string = baseUrl

export const anonKey: string = (typeof import.meta !== 'undefined' && (import.meta as any).env?.VITE_SUPABASE_ANON_KEY)
  ? (import.meta as any).env.VITE_SUPABASE_ANON_KEY as string
  : publicAnonKey

export const projectRef: string = (() => {
  try {
    const url = new URL(baseUrl)
    const host = url.hostname // e.g., xxxxxx.supabase.co
    return host.split('.')[0]
  } catch {
    // Fallback to legacy value
    return projectId
  }
})()
